name: Company Review System

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  deploy:
    runs-on: self-hosted  # Indicates that the job will run on a self-hosted runner

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Execute automate.sh on Self-Hosted Runner
      run: |
        sudo rm -rf /home/ubuntu/actions-runner/_work/Python_Django_with_Devops
        bash /home/ubuntu/actions-runner/_work/Python_Django_with_Devops/Python_Django_with_Devops/Company_Review_System/automate.sh
